"""Authored light-practice questions, with explicit constraints and distractors.

The first choice is the answer key. No model is used at runtime. Keep existing
IDs and semantics stable; add a new ID when changing what a question tests.
"""

CHOICES = {
    "fill-lower-bound": ("fill", "Binary Search", "Find the first occurrence",
        "Return the first index with nums[index] >= target, or len(nums) if none exists. nums is sorted; hi is exclusive. Fill the branch for nums[mid] >= target.",
        "def lower_bound(nums, target):\n    lo, hi = 0, len(nums)\n    while lo < hi:\n        mid = (lo + hi) // 2\n        if nums[mid] < target:\n            lo = mid + 1\n        else:\n            ___\n    return lo",
        ["hi = mid", "hi = mid - 1", "lo = mid + 1", "return mid"],
        "mid may be the first qualifying index, so keep it as the boundary. Returning immediately can pick a later duplicate; subtracting one can discard the answer."),
    "fill-prefix-count": ("fill", "Arrays & Hashing", "Count prefixes, including the empty one",
        "Count all nonempty contiguous subarrays summing to k. Integers may be negative or zero. How should the frequency map start?",
        "def count_sums(nums, k):\n    freq = ___\n    total = answer = 0\n    for x in nums:\n        total += x\n        answer += freq.get(total - k, 0)\n        freq[total] = freq.get(total, 0) + 1\n    return answer",
        ["{0: 1}", "{}", "{k: 1}", "{0: 0}"],
        "The empty prefix has sum zero and occurs once. It allows a subarray starting at index zero to be counted when its prefix sum equals k. Query before inserting the current prefix to avoid counting an empty subarray."),
    "fill-two-sum": ("fill", "Arrays & Hashing", "Use two distinct positions",
        "Return whether two distinct positions sum to target. Which membership test belongs before adding x to seen?",
        "def has_pair(nums, target):\n    seen = set()\n    for x in nums:\n        if ___:\n            return True\n        seen.add(x)\n    return False",
        ["target - x in seen", "x in seen", "target + x in seen", "target in seen"],
        "The earlier value must equal target - x. Because x is inserted afterward, the same position cannot match itself, while two separate equal values can still form a pair."),
    "fill-product-prefix": ("fill", "Arrays & Hashing", "Exclude the current factor",
        "out[i] must become the product of nums strictly before i, using 1 for the empty product. Fill the loop body in the correct order.",
        "def prefixes(nums):\n    out = [1] * len(nums)\n    product = 1\n    for i, x in enumerate(nums):\n        ___\n    return out",
        ["out[i] = product; product *= x", "product *= x; out[i] = product", "out[i] = x; product *= x", "out[i] = product; product += x"],
        "Store the product before multiplying by the current element. This excludes nums[i] and still works with zeros, without division."),
    "fill-reverse-list": ("fill", "Linked List", "Preserve the rest of the list",
        "Reverse a singly linked list in place. Each node has .next. What must be saved before changing cur.next?",
        "def reverse(head):\n    prev, cur = None, head\n    while cur is not None:\n        nxt = ___\n        cur.next = prev\n        prev = cur\n        cur = nxt\n    return prev",
        ["cur.next", "prev", "head", "cur"],
        "Saving the old next pointer is the only way to continue through the unprocessed suffix after cur.next has been reversed."),
    "fill-tree-depth": ("fill", "Trees", "Combine two subtree heights",
        "Depth counts nodes on the longest root-to-leaf path. An empty tree has depth 0. Fill the recurrence for nodes with .left and .right.",
        "def depth(node):\n    if node is None:\n        return 0\n    return ___",
        ["1 + max(depth(node.left), depth(node.right))", "1 + depth(node.left) + depth(node.right)", "max(depth(node.left), depth(node.right))", "1 + min(depth(node.left), depth(node.right))"],
        "A path follows one subtree, so take the larger height and count the current node. Summing subtree depths does not describe a single path."),
    "fill-bst-bounds": ("fill", "Trees", "Carry ancestor bounds",
        "Validate a strict BST: all values in the left subtree must be smaller and all in the right larger, with no duplicates. What bounds belong in the left recursive call?",
        "def valid(node, low=float('-inf'), high=float('inf')):\n    if node is None:\n        return True\n    if not low < node.val < high:\n        return False\n    return valid(node.left, ___) and valid(node.right, node.val, high)",
        ["low, node.val", "float('-inf'), node.val", "low, high", "node.val, high"],
        "The left subtree inherits every lower bound imposed by an ancestor, while the current value tightens its upper bound. Resetting low can accept a descendant on the wrong side of an ancestor."),
    "fill-trie-word": ("fill", "Tries", "A prefix is not always a word",
        "Trie nodes have .children (a character-to-node map) and .is_word (a boolean). After matching every character, how do you check that the whole word was inserted?",
        "def contains(root, word):\n    node = root\n    for ch in word:\n        if ch not in node.children:\n            return False\n        node = node.children[ch]\n    return ___",
        ["node.is_word", "True", "not node.children", "bool(node.children)"],
        "A path only proves a prefix exists. A terminal flag distinguishes inserted words from prefixes; an inserted word can also have children."),
    "fill-heap-k": ("fill", "Heap / Priority Queue", "Keep only the largest k",
        "For k >= 1, retain the k largest values seen so far in a min-heap. Duplicates count separately. Which condition makes the heap drop one item?",
        "import heapq\ndef largest_k(nums, k):\n    heap = []\n    for x in nums:\n        heapq.heappush(heap, x)\n        if ___:\n            heapq.heappop(heap)\n    return sorted(heap)",
        ["len(heap) > k", "len(heap) >= k", "x > heap[0]", "len(heap) < k"],
        "After pushing, discard the minimum only when the size exceeds k. Using >= k leaves just k - 1 values; the minimum is allowed to remain until capacity is exceeded."),
    "fill-topological": ("fill", "Graphs", "Release a dependency",
        "graph is a directed adjacency list over 0..n-1. indegree initially counts incoming edges. When removing an edge node -> nxt, how should its target's indegree change?",
        "from collections import deque\ndef order(graph, indegree):\n    queue = deque(i for i, d in enumerate(indegree) if d == 0)\n    out = []\n    while queue:\n        node = queue.popleft()\n        out.append(node)\n        for nxt in graph[node]:\n            ___\n            if indegree[nxt] == 0:\n                queue.append(nxt)\n    return out",
        ["indegree[nxt] -= 1", "indegree[node] -= 1", "indegree[nxt] = 0", "indegree[nxt] += 1"],
        "Remove exactly this incoming edge. Enqueue the target only after its last prerequisite is removed; forcing zero can release it too early."),
    "fill-union-roots": ("fill", "Graphs", "Merge representatives",
        "parent describes a disjoint-set forest; find returns a root. Which update joins the entire component of a to the entire component of b?",
        "def union(parent, a, b):\n    def find(x):\n        while parent[x] != x:\n            x = parent[x]\n        return x\n    ra, rb = find(a), find(b)\n    if ra != rb:\n        ___",
        ["parent[ra] = rb", "parent[a] = b", "parent[rb] = b", "parent[a] = a"],
        "Link roots so every member of one component reaches the other root. Reparenting an arbitrary internal node can split its old component instead of merging the two components."),
    "fill-coin-combinations": ("fill", "1-D DP", "Extend a coin combination",
        "coins contains distinct positive denominations; each is reusable. Count unordered combinations totaling amount >= 0. Fill the update.",
        "def combinations(coins, amount):\n    ways = [0] * (amount + 1)\n    ways[0] = 1\n    for coin in coins:\n        for total in range(coin, amount + 1):\n            ___\n    return ways[amount]",
        ["ways[total] += ways[total - coin]", "ways[total] = ways[total - coin]", "ways[total] += 1", "ways[total] += ways[coin]"],
        "Append the current denomination to every combination for total - coin. Add those to combinations that omit this denomination. The outer coin loop prevents counting different orders separately."),
    "fill-knapsack-direction": ("fill", "2-D DP", "Use an item only once",
        "items contains (positive weight, nonnegative value) pairs. Each item can be used at most once. Fill the capacity loop for 0/1 knapsack.",
        "def best_value(items, capacity):\n    dp = [0] * (capacity + 1)\n    for weight, value in items:\n        for c in ___:\n            dp[c] = max(dp[c], dp[c - weight] + value)\n    return dp[capacity]",
        ["range(capacity, weight - 1, -1)", "range(weight, capacity + 1)", "range(capacity, weight, -1)", "range(weight + 1, capacity + 1)"],
        "Descending capacities read states from before the current item was used. Ascending capacities can reuse that item repeatedly. Include c == weight so the item fits at its exact weight."),
    "fill-backtrack-copy": ("fill", "Backtracking", "Save a snapshot of a path",
        "Return every subset of distinct input values. path is mutated after visiting each branch. What should be appended at a leaf?",
        "def subsets(nums):\n    out, path = [], []\n    def visit(i):\n        if i == len(nums):\n            out.append(___)\n            return\n        visit(i + 1)\n        path.append(nums[i])\n        visit(i + 1)\n        path.pop()\n    visit(0)\n    return out",
        ["path.copy()", "path", "nums", "[]"],
        "Store a shallow copy of the integer list. Appending path itself stores the same mutable object repeatedly; later pops change every saved reference."),
    "fill-merge-end": ("fill", "Intervals", "Merge without shrinking",
        "Merge closed intervals [start, end] with start <= end. Touching endpoints count as overlap. When an interval overlaps the last merged one, fill the new end.",
        "def merge(intervals):\n    out = []\n    for start, end in sorted(intervals):\n        if not out or start > out[-1][1]:\n            out.append([start, end])\n        else:\n            out[-1][1] = ___\n    return out",
        ["max(out[-1][1], end)", "end", "min(out[-1][1], end)", "out[-1][1] + end"],
        "Keep the farther endpoint. A nested interval must not shrink an already covered range; assigning end directly fails on [1, 10] followed by [2, 3]."),
    "fill-three-sum-skip": ("fill", "Two Pointers", "Skip a repeated anchor",
        "Return each unique triple of values summing to zero exactly once. Fill the condition that skips a duplicate anchor without losing triples that use repeated values.",
        "def three_sum(nums):\n    nums = sorted(nums)\n    out = []\n    for i in range(len(nums) - 2):\n        if ___:\n            continue\n        lo, hi = i + 1, len(nums) - 1\n        while lo < hi:\n            s = nums[i] + nums[lo] + nums[hi]\n            if s < 0:\n                lo += 1\n            elif s > 0:\n                hi -= 1\n            else:\n                out.append([nums[i], nums[lo], nums[hi]])\n                lo += 1\n                while lo < hi and nums[lo] == nums[lo - 1]:\n                    lo += 1\n    return out",
        ["i > 0 and nums[i] == nums[i - 1]", "nums[i] == nums[i + 1]", "nums[i] > 0 and nums[i] == nums[i - 1]", "[nums[i]] in out"],
        "Skip an anchor only after its first occurrence has run. Comparing with the next value skips the first copy instead, losing triples such as [-1, -1, 2] that need both."),
    "fill-min-stack": ("fill", "Stack", "Remember the minimum at each depth",
        "get_min must run in O(1) and stay correct after pops. Each entry stores a value and the minimum of the stack from the bottom through that entry. Fill the stored minimum.",
        "class MinStack:\n    def __init__(self):\n        self.items = []  # (value, minimum through here)\n    def push(self, x):\n        self.items.append((x, ___))\n    def pop(self):\n        self.items.pop()\n    def get_min(self):\n        return self.items[-1][1]",
        ["min(x, self.items[-1][1]) if self.items else x", "x", "min(x, self.items[-1][0]) if self.items else x", "min(x, self.items[0][0]) if self.items else x"],
        "The new minimum is the smaller of x and the minimum beneath it. Comparing only with the top value forgets a smaller value deeper down. Storing it per entry means a pop restores the earlier minimum automatically."),
    "fill-warmer-days": ("fill", "Stack", "Pop only strictly cooler days",
        "answer[j] is the number of days after j until a strictly warmer temperature, or 0. The stack holds indices still waiting. Fill the loop condition.",
        "def wait_days(temps):\n    answer = [0] * len(temps)\n    stack = []  # indices without a warmer day yet\n    for i, t in enumerate(temps):\n        while ___:\n            j = stack.pop()\n            answer[j] = i - j\n        stack.append(i)\n    return answer",
        ["stack and temps[stack[-1]] < t", "stack and temps[stack[-1]] <= t", "stack and stack[-1] < t", "stack and temps[stack[0]] < t"],
        "Compare temperatures, not indices, and resolve only strictly cooler days. An equal day is not warmer, so it must keep waiting. The stack's top is its coolest waiting day."),
    "fill-rotated-half": ("fill", "Binary Search", "Identify the sorted half",
        "nums is an ascending array of distinct values, rotated by an unknown amount. Fill the test that the left half nums[lo..mid] is sorted.",
        "def search(nums, target):\n    lo, hi = 0, len(nums) - 1\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        if nums[mid] == target:\n            return mid\n        if ___:\n            if nums[lo] <= target < nums[mid]:\n                hi = mid - 1\n            else:\n                lo = mid + 1\n        else:\n            if nums[mid] < target <= nums[hi]:\n                lo = mid + 1\n            else:\n                hi = mid - 1\n    return -1",
        ["nums[lo] <= nums[mid]", "nums[lo] < nums[mid]", "nums[mid] <= nums[hi]", "nums[lo] <= target"],
        "The left half is sorted when its first value is at most its middle value. Use <=: when lo == mid the one-element half is sorted, and strict < would send the search the wrong way."),
    "fill-cycle-guard": ("fill", "Linked List", "Guard the double step",
        "Detect a cycle with slow and fast pointers. Nodes have .next; a list may be empty. Fill the loop condition so the loop never dereferences None.",
        "def has_cycle(head):\n    slow = fast = head\n    while ___:\n        slow = slow.next\n        fast = fast.next.next\n        if slow is fast:\n            return True\n    return False",
        ["fast and fast.next", "fast.next", "slow and fast", "slow is not fast"],
        "fast advances two links, so both fast and fast.next must exist. If either is None the list ends, so there is no cycle. slow trails fast and needs no separate check."),
    "fill-merge-tail": ("fill", "Linked List", "Attach the leftover run",
        "Merge two sorted linked lists of Node(val, next). One list can run out before the other. Fill the final link.",
        "def merge(a, b):\n    dummy = tail = Node(0)\n    while a and b:\n        if a.val <= b.val:\n            tail.next, a = a, a.next\n        else:\n            tail.next, b = b, b.next\n        tail = tail.next\n    tail.next = ___\n    return dummy.next",
        ["a or b", "None", "a", "b"],
        "At most one list still has nodes, and they are already sorted and at least as large as everything merged. Link whichever remains; a or b picks it without a branch."),
    "fill-level-width": ("fill", "Trees", "Freeze the level size",
        "Return node values grouped by depth, top to bottom. Children are appended to the same queue during the loop. Fill the range.",
        "from collections import deque\ndef levels(root):\n    out = []\n    queue = deque([root] if root else [])\n    while queue:\n        level = []\n        for _ in range(___):\n            node = queue.popleft()\n            level.append(node.val)\n            for child in (node.left, node.right):\n                if child:\n                    queue.append(child)\n        out.append(level)\n    return out",
        ["len(queue)", "1", "2 ** len(out)", "len(out) + 1"],
        "range(len(queue)) is evaluated once, before this level's children are added, so it counts exactly the current level. Assuming a perfect tree's 2^depth nodes fails on any missing child."),
    "fill-diameter": ("fill", "Trees", "Longest path through a node",
        "The diameter is the number of edges on the longest path between any two nodes. height returns nodes on the longest downward path. Fill the candidate for a path that bends at node.",
        "def diameter(root):\n    best = 0\n    def height(node):\n        nonlocal best\n        if node is None:\n            return 0\n        left, right = height(node.left), height(node.right)\n        best = max(best, ___)\n        return 1 + max(left, right)\n    height(root)\n    return best",
        ["left + right", "left + right + 1", "1 + max(left, right)", "max(left, right)"],
        "A path bending at node goes down both sides. A subtree of height h contributes h edges once you count the edge from node to it, so the path has left + right edges. Adding 1 counts nodes instead."),
    "fill-trie-wildcard": ("fill", "Tries", "A dot matches any child",
        "Search a trie where '.' matches any single letter. Nodes have .children (letter → node) and .is_word. Fill the wildcard branch.",
        "def search(node, word, i=0):\n    if i == len(word):\n        return node.is_word\n    ch = word[i]\n    if ch == '.':\n        return ___\n    child = node.children.get(ch)\n    return child is not None and search(child, word, i + 1)",
        ["any(search(child, word, i + 1) for child in node.children.values())", "all(search(child, word, i + 1) for child in node.children.values())", "any(search(child, word, i) for child in node.children.values())", "search(node, word, i + 1)"],
        "The dot consumes one letter along some edge, so try every child at the next position and succeed if any match. all would require every branch to match and succeeds vacuously at a leaf."),
    "fill-heap-tiebreak": ("fill", "Heap / Priority Queue", "Break ties before comparing nodes",
        "Merge k sorted linked lists. Node objects do not support <, and values can repeat across lists. Entries start as (value, list index, node). Fill the next entry.",
        "import heapq\ndef merge_k(lists):\n    heap = [(node.val, i, node) for i, node in enumerate(lists) if node]\n    heapq.heapify(heap)\n    out = []\n    while heap:\n        _, i, node = heapq.heappop(heap)\n        out.append(node.val)\n        if node.next:\n            heapq.heappush(heap, ___)\n    return out",
        ["(node.next.val, i, node.next)", "(node.val, i, node.next)", "(i, node.next.val, node.next)", "(node.next.val, 0, node.next)"],
        "Order by the next node's value. The list index breaks ties, and each list has at most one entry in the heap, so the index is unique and Python never compares two nodes. A constant tiebreaker still reaches the nodes on equal values."),
    "fill-permutation-used": ("fill", "Backtracking", "Skip positions already on the path",
        "Return every ordering of distinct values. used[i] tracks whether position i is on the current path. Fill the skip condition.",
        "def permutations(nums):\n    out, path = [], []\n    used = [False] * len(nums)\n    def visit():\n        if len(path) == len(nums):\n            out.append(path.copy())\n            return\n        for i, x in enumerate(nums):\n            if ___:\n                continue\n            used[i] = True\n            path.append(x)\n            visit()\n            path.pop()\n            used[i] = False\n    visit()\n    return out",
        ["used[i]", "not used[i]", "i in path", "i > 0 and x == nums[i - 1]"],
        "Each position appears once per ordering, so skip positions already chosen. path holds values rather than positions; i in path confuses the two."),
    "fill-combination-reuse": ("fill", "Backtracking", "Reuse without reordering",
        "candidates are distinct positive integers; each may be used any number of times. Return each combination summing to target once, ignoring order. Fill the next start index.",
        "def combination_sum(candidates, target):\n    out, path = [], []\n    def visit(start, remaining):\n        if remaining == 0:\n            out.append(path.copy())\n            return\n        for j in range(start, len(candidates)):\n            if candidates[j] <= remaining:\n                path.append(candidates[j])\n                visit(___, remaining - candidates[j])\n                path.pop()\n    visit(0, target)\n    return out",
        ["j", "j + 1", "start", "0"],
        "Passing j allows the same candidate again but never an earlier one, so each combination appears in one nondecreasing order. j + 1 forbids reuse; start or 0 revisits earlier candidates and duplicates orderings."),
    "fill-island-bounds": ("fill", "Graphs", "Negative indices wrap in Python",
        "Count 4-directionally connected islands of 1s in a rectangular grid, sinking visited land. Fill the condition for a cell that should be sunk.",
        "def islands(grid):\n    rows, cols = len(grid), len(grid[0])\n    def sink(r, c):\n        if not (___):\n            return\n        grid[r][c] = 0\n        for dr, dc in ((1, 0), (-1, 0), (0, 1), (0, -1)):\n            sink(r + dr, c + dc)\n    count = 0\n    for r in range(rows):\n        for c in range(cols):\n            if grid[r][c] == 1:\n                sink(r, c)\n                count += 1\n    return count",
        ["0 <= r < rows and 0 <= c < cols and grid[r][c] == 1", "r < rows and c < cols and grid[r][c] == 1", "0 <= r < rows and 0 <= c < cols", "0 <= r <= rows and 0 <= c <= cols and grid[r][c] == 1"],
        "Check both bounds before indexing. In Python grid[r][-1] is the last column rather than an error, so omitting the lower bounds silently joins land on opposite edges."),
    "fill-dijkstra-improve": ("fill", "Advanced Graphs", "Only a shorter path updates",
        "graph[u] lists (v, weight) pairs with nonnegative weights. dist holds the best distance found so far; missing means unreached. Fill the relaxation test.",
        "import heapq\ndef shortest(graph, start):\n    dist = {start: 0}\n    heap = [(0, start)]\n    while heap:\n        d, node = heapq.heappop(heap)\n        if d > dist[node]:\n            continue  # stale entry\n        for nxt, w in graph[node]:\n            nd = d + w\n            if ___:\n                dist[nxt] = nd\n                heapq.heappush(heap, (nd, nxt))\n    return dist",
        ["nd < dist.get(nxt, float('inf'))", "nxt not in dist", "nd > dist.get(nxt, float('inf'))", "nd < dist.get(nxt, 0)"],
        "A vertex's first tentative distance can still be improved by a longer path of cheaper edges. Update whenever the new distance is smaller; treat unreached as infinity."),
    "fill-lis-condition": ("fill", "1-D DP", "Strictly increasing",
        "dp[i] is the length of the longest strictly increasing subsequence ending at i. Fill the condition for extending a subsequence ending at j.",
        "def lis(nums):\n    dp = [1] * len(nums)\n    for i in range(len(nums)):\n        for j in range(i):\n            if ___:\n                dp[i] = max(dp[i], dp[j] + 1)\n    return max(dp, default=0)",
        ["nums[j] < nums[i]", "nums[j] <= nums[i]", "dp[j] < dp[i]", "j < i"],
        "nums[i] can follow a subsequence ending at j only if it is strictly larger. <= would allow equal values; comparing dp values tests lengths, not order."),
    "fill-rob-rolling": ("fill", "1-D DP", "Take this house or skip it",
        "Values are nonnegative. Choose values with no two adjacent. prev1 is the best through the previous house and prev2 the best through the one before. Fill the new prev1.",
        "def rob(nums):\n    prev2 = prev1 = 0\n    for x in nums:\n        prev2, prev1 = prev1, ___\n    return prev1",
        ["max(prev1, prev2 + x)", "prev2 + x", "max(prev1, prev2) + x", "max(prev1 + x, prev2)"],
        "Either skip x and keep prev1, or take x with the best total that ends at least two houses back. Adding x to prev1 would allow adjacent houses."),
    "fill-edit-mismatch": ("fill", "2-D DP", "Three ways to fix a mismatch",
        "dp[i][j] is the fewest insertions, deletions and replacements turning a[:i] into b[:j]. Fill the mismatch case.",
        "def edit_distance(a, b):\n    dp = [[0] * (len(b) + 1) for _ in range(len(a) + 1)]\n    for i in range(len(a) + 1):\n        dp[i][0] = i\n    for j in range(len(b) + 1):\n        dp[0][j] = j\n    for i in range(1, len(a) + 1):\n        for j in range(1, len(b) + 1):\n            if a[i - 1] == b[j - 1]:\n                dp[i][j] = dp[i - 1][j - 1]\n            else:\n                dp[i][j] = 1 + ___\n    return dp[-1][-1]",
        ["min(dp[i - 1][j], dp[i][j - 1], dp[i - 1][j - 1])", "min(dp[i - 1][j], dp[i][j - 1])", "dp[i - 1][j - 1]", "max(dp[i - 1][j], dp[i][j - 1], dp[i - 1][j - 1])"],
        "The last operation is a deletion (up), an insertion (left) or a replacement (diagonal). Take the cheapest. Omitting the diagonal forbids replacement; using only it forbids length changes."),
    "fill-jump-stuck": ("fill", "Greedy", "Detect an unreachable index",
        "nums[i] is the longest jump from index i. Return whether the last index is reachable from index 0. Fill the failure condition.",
        "def can_reach_end(nums):\n    reach = 0\n    for i, x in enumerate(nums):\n        if ___:\n            return False\n        reach = max(reach, i + x)\n    return True",
        ["i > reach", "i >= reach", "x == 0", "reach < len(nums) - 1"],
        "Every index up to reach is reachable. The first index beyond it cannot be reached, nor can anything after it. A zero is harmless if some earlier jump passes it."),
    "fill-gas-restart": ("fill", "Greedy", "Restart after a failed stretch",
        "Driving from station i to i + 1 gains gas[i] - cost[i]; the route is circular. Return a start that completes the loop, or -1. Fill the new start after the tank goes negative.",
        "def start_station(gas, cost):\n    if sum(gas) < sum(cost):\n        return -1\n    start = tank = 0\n    for i in range(len(gas)):\n        tank += gas[i] - cost[i]\n        if tank < 0:\n            start = ___\n            tank = 0\n    return start",
        ["i + 1", "i", "start + 1", "0"],
        "Every station from start through i reaches i with no more gas than start did, so none can pass i either. Restart after i. A nonnegative total then guarantees the final start completes the loop."),
    "fill-erase-overlap": ("fill", "Intervals", "Touching intervals may both stay",
        "Intervals are [start, finish) with start < finish; touching endpoints do not overlap. Return the fewest removals leaving no overlap. Fill the keep condition.",
        "def min_removals(intervals):\n    kept, end = 0, float('-inf')\n    for start, finish in sorted(intervals, key=lambda x: x[1]):\n        if ___:\n            kept += 1\n            end = finish\n    return len(intervals) - kept",
        ["start >= end", "start > end", "finish >= end", "start >= finish"],
        "Scanning by finish time, keep an interval when it starts no earlier than the last kept finish. Equality is allowed because these intervals only touch."),
    "fill-rotate-reverse": ("fill", "Math & Geometry", "Reverse in place, not a copy",
        "Rotate an n × n matrix 90° clockwise, in place. The transpose is done. Fill the second step.",
        "def rotate(matrix):\n    n = len(matrix)\n    for r in range(n):\n        for c in range(r + 1, n):\n            matrix[r][c], matrix[c][r] = matrix[c][r], matrix[r][c]\n    for row in matrix:\n        ___",
        ["row.reverse()", "row = row[::-1]", "row.sort()", "matrix.reverse()"],
        "Reversing each transposed row completes a clockwise rotation. row = row[::-1] only rebinds the loop variable to a new list; the matrix is unchanged."),
    "fill-fast-power": ("fill", "Math & Geometry", "Square the base, halve the exponent",
        "Compute base ** exp for an integer exp >= 0 with O(log exp) multiplications. Fill the exponent update.",
        "def power(base, exp):\n    result = 1\n    while exp:\n        if exp & 1:\n            result *= base\n        base *= base\n        ___\n    return result",
        ["exp >>= 1", "exp -= 1", "exp &= exp - 1", "exp //= 4"],
        "Each pass consumes one binary digit of exp: multiply in base when that bit is set, square base for the next bit, then shift the bit away."),
    "fill-reverse-digits": ("fill", "Math & Geometry", "Peel the last digit",
        "Reverse the decimal digits of an integer n >= 0; for example, 120 becomes 21. Fill the digit appended to rev.",
        "def reverse_digits(n):\n    rev = 0\n    while n:\n        rev = rev * 10 + ___\n        n //= 10\n    return rev",
        ["n % 10", "n // 10", "rev % 10", "n"],
        "n % 10 is the last digit of n. Shift rev left one decimal place and append that digit, then drop it from n."),
    "fill-count-bits": ("fill", "Bit Manipulation", "Drop one set bit per step",
        "Count the 1 bits of an integer n >= 0 using one loop iteration per set bit. Fill the update.",
        "def ones(n):\n    count = 0\n    while n:\n        n &= ___\n        count += 1\n    return count",
        ["n - 1", "n >> 1", "~n", "n // 10"],
        "n - 1 flips the lowest set bit and the zeros below it, so n & (n - 1) clears exactly that bit. The loop runs once per set bit."),
    "fill-missing-xor": ("fill", "Bit Manipulation", "Start with the missing index",
        "nums holds distinct values from 0 through len(nums), with exactly one missing. Fill the starting value so XOR cancels every present value.",
        "def missing(nums):\n    result = ___\n    for i, x in enumerate(nums):\n        result ^= i ^ x\n    return result",
        ["len(nums)", "0", "len(nums) - 1", "nums[0]"],
        "The indices supply 0 through len(nums) - 1. Starting at len(nums) completes the full range, so every present value cancels with itself and only the missing one remains."),
    "fill-anagram-key": ("fill", "Arrays & Hashing", "A key every anagram shares",
        "Group words that are anagrams of each other; letters may repeat. Fill a dictionary key that is equal exactly for anagrams.",
        "def group(words):\n    groups = {}\n    for word in words:\n        key = ___\n        groups.setdefault(key, []).append(word)\n    return list(groups.values())",
        ["tuple(sorted(word))", "sorted(word)", "frozenset(word)", "len(word)"],
        "Sorted letters are identical exactly for anagrams, and a tuple is hashable. A list cannot be a key; a set of letters forgets counts, so 'aab' and 'abb' would collide."),
    "fill-top-k-buckets": ("fill", "Heap / Priority Queue", "Bucket by frequency",
        "Return the k most frequent values in O(n) time using buckets indexed by frequency. Fill the bucket index.",
        "from collections import Counter\ndef top_k(nums, k):\n    counts = Counter(nums)\n    buckets = [[] for _ in range(len(nums) + 1)]\n    for x, count in counts.items():\n        buckets[___].append(x)\n    out = []\n    for bucket in reversed(buckets):\n        out.extend(bucket)\n    return out[:k]",
        ["count", "len(nums) - count", "k", "x % len(buckets)"],
        "A frequency is between 1 and len(nums), so it indexes a bucket directly. Reading buckets from the highest index yields the most frequent values first, without sorting."),
    "fill-brackets-end": ("fill", "Stack", "Leftover openers",
        "Return whether s contains correctly nested (), [] and {} and nothing else. Fill the final return.",
        "def valid(s):\n    pairs = {')': '(', ']': '[', '}': '{'}\n    stack = []\n    for ch in s:\n        if ch in pairs:\n            if not stack or stack.pop() != pairs[ch]:\n                return False\n        else:\n            stack.append(ch)\n    return ___",
        ["not stack", "True", "bool(stack)", "len(stack) <= 1"],
        "Every closer was checked during the scan, but an opener might never be closed. The string is valid only when no openers remain; '((' passes the loop but is invalid."),
    "fill-matrix-index": ("fill", "Binary Search", "Map a flat index to a cell",
        "Rows are sorted and each row starts after the previous row ends, so the matrix reads as one sorted list. Fill the row index for flat position mid.",
        "def search(matrix, target):\n    rows, cols = len(matrix), len(matrix[0])\n    lo, hi = 0, rows * cols - 1\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        value = matrix[___][mid % cols]\n        if value == target:\n            return True\n        if value < target:\n            lo = mid + 1\n        else:\n            hi = mid - 1\n    return False",
        ["mid // cols", "mid // rows", "mid % rows", "mid // (cols + 1)"],
        "Each row holds cols values, so flat index mid is in row mid // cols at column mid % cols. Dividing by rows works only for square matrices."),
    "fill-eating-hours": ("fill", "Binary Search", "Round the hours up",
        "Each hour you eat up to speed bananas from one pile, and a pile's partial hour still costs a full hour. Fill the hours for pile p.",
        "def min_speed(piles, h):  # h >= len(piles)\n    lo, hi = 1, max(piles)\n    while lo < hi:\n        speed = (lo + hi) // 2\n        hours = sum(___ for p in piles)\n        if hours <= h:\n            hi = speed\n        else:\n            lo = speed + 1\n    return lo",
        ["(p + speed - 1) // speed", "p // speed", "p // speed + 1", "round(p / speed)"],
        "A pile takes ceil(p / speed) hours. Floor division undercounts partial hours; adding one always overcounts exact multiples."),
    "fill-nth-lead": ("fill", "Linked List", "How far ahead the leader starts",
        "Remove the nth node from the end (1 <= n <= length). Both pointers start at a dummy node before head. Fill the leader's head start.",
        "def remove_nth(head, n):\n    dummy = Node(0, head)\n    lead = trail = dummy\n    for _ in range(___):\n        lead = lead.next\n    while lead is not None:\n        lead = lead.next\n        trail = trail.next\n    trail.next = trail.next.next\n    return dummy.next",
        ["n + 1", "n", "n - 1", "n + 2"],
        "trail must stop on the node before the target. A gap of n + 1 links puts it there when lead reaches None; the dummy makes removing the head work too."),
    "fill-invert-tree": ("fill", "Trees", "Swap whole subtrees",
        "Mirror a binary tree in place, returning its root. Nodes have .left and .right. Fill the assignment.",
        "def invert(node):\n    if node is None:\n        return None\n    node.left, node.right = ___\n    return node",
        ["invert(node.right), invert(node.left)", "invert(node.left), invert(node.right)", "node.right, node.left", "invert(node.right), node.left"],
        "Swap the children and mirror each of them. The right-hand side is evaluated completely before assignment. Swapping only at the root leaves the subtrees unmirrored."),
    "fill-same-tree": ("fill", "Trees", "Same shape and values",
        "Return whether two binary trees are identical in structure and values. Fill the recursive case.",
        "def same(a, b):\n    if a is None or b is None:\n        return a is b\n    return ___",
        ["a.val == b.val and same(a.left, b.left) and same(a.right, b.right)", "a.val == b.val and same(a.left, b.right) and same(a.right, b.left)", "same(a.left, b.left) and same(a.right, b.right)", "a.val == b.val or same(a.left, b.left) and same(a.right, b.right)"],
        "Compare the roots, then left with left and right with right. Crossing sides tests mirror images; skipping the value compares only shape."),
    "fill-task-idle": ("fill", "Heap / Priority Queue", "Frames around the busiest task",
        "Tasks take one unit each; identical tasks must be at least n units apart, and idle units are allowed. top is the highest task count and ties is how many tasks have it. Fill the frame length.",
        "from collections import Counter\ndef least_time(tasks, n):\n    counts = Counter(tasks).values()\n    top = max(counts)\n    ties = sum(c == top for c in counts)\n    return max(len(tasks), ___)",
        ["(top - 1) * (n + 1) + ties", "top * (n + 1)", "(top - 1) * n + ties", "(top - 1) * (n + 1)"],
        "The busiest task forms top - 1 full frames of n + 1 slots, then a final partial frame holding each tied task once. If other tasks overflow the idle slots, no idling is needed and the answer is len(tasks)."),
    "fill-subsets-dupes": ("fill", "Backtracking", "Skip equal siblings, not equal descendants",
        "Return every distinct subset of a list that may contain duplicates. Fill the skip condition.",
        "def subsets(nums):\n    nums = sorted(nums)\n    out, path = [], []\n    def visit(start):\n        out.append(path.copy())\n        for j in range(start, len(nums)):\n            if ___:\n                continue\n            path.append(nums[j])\n            visit(j + 1)\n            path.pop()\n    visit(0)\n    return out",
        ["j > start and nums[j] == nums[j - 1]", "j > 0 and nums[j] == nums[j - 1]", "nums[j] in path", "j > start and nums[j] == nums[start]"],
        "At one depth, choosing the second of two equal values repeats the branch from the first. Deeper in the same branch, the repeated value must stay available so subsets like [1, 1] exist."),
    "fill-cycle-colors": ("fill", "Graphs", "Only the current path signals a cycle",
        "Detect a cycle in a directed graph using three states. Fill the state that means an edge points back into the current DFS path.",
        "def has_cycle(n, edges):\n    graph = [[] for _ in range(n)]\n    for a, b in edges:\n        graph[a].append(b)\n    state = [0] * n  # 0 unvisited, 1 on the current path, 2 finished\n    def visit(node):\n        state[node] = 1\n        for nxt in graph[node]:\n            if state[nxt] == ___:\n                return True\n            if state[nxt] == 0 and visit(nxt):\n                return True\n        state[node] = 2\n        return False\n    return any(state[v] == 0 and visit(v) for v in range(n))",
        ["1", "2", "0", "-1"],
        "Reaching a vertex still on the current path closes a loop. A finished vertex was fully explored without finding one, so reaching it again, e.g. in a diamond, is not a cycle."),
    "fill-rounds-copy": ("fill", "Advanced Graphs", "Relax from last round's distances",
        "Find the cheapest price from src to dst using at most k stops (k + 1 flights). Each round must add at most one flight. Fill prev.",
        "def cheapest(n, flights, src, dst, k):\n    dist = [float('inf')] * n\n    dist[src] = 0\n    for _ in range(k + 1):\n        prev = ___\n        for a, b, price in flights:\n            if prev[a] + price < dist[b]:\n                dist[b] = prev[a] + price\n    return -1 if dist[dst] == float('inf') else dist[dst]",
        ["dist.copy()", "dist", "[float('inf')] * n", "[0] * n"],
        "Reading a snapshot means every route found in round r uses at most r flights. Aliasing dist lets one round chain several flights, exceeding the stop limit."),
    "fill-decode-pair": ("fill", "1-D DP", "A valid two-digit code",
        "Count decodings of a digit string where '1' to '26' map to letters and '0' alone is invalid. ways[i] counts decodings of s[:i]. Fill the two-digit test.",
        "def decodings(s):\n    ways = [1] + [0] * len(s)\n    for i in range(1, len(s) + 1):\n        if s[i - 1] != '0':\n            ways[i] += ways[i - 1]\n        if i >= 2 and ___:\n            ways[i] += ways[i - 2]\n    return ways[-1]",
        ["10 <= int(s[i - 2:i]) <= 26", "int(s[i - 2:i]) <= 26", "s[i - 2] != '0'", "10 <= int(s[i - 2:i]) < 26"],
        "A two-digit code must be 10 through 26. '06' is not a letter, so a leading zero disqualifies it, and 26 is 'z'."),
    "fill-lcs-match": ("fill", "2-D DP", "Use each matched character once",
        "dp[i][j] is the length of the longest common subsequence of a[:i] and b[:j]. Fill the case where a[i - 1] == b[j - 1].",
        "def lcs(a, b):\n    dp = [[0] * (len(b) + 1) for _ in range(len(a) + 1)]\n    for i in range(1, len(a) + 1):\n        for j in range(1, len(b) + 1):\n            if a[i - 1] == b[j - 1]:\n                dp[i][j] = ___\n            else:\n                dp[i][j] = max(dp[i - 1][j], dp[i][j - 1])\n    return dp[-1][-1]",
        ["dp[i - 1][j - 1] + 1", "max(dp[i - 1][j], dp[i][j - 1]) + 1", "dp[i - 1][j] + 1", "dp[i - 1][j - 1]"],
        "A match pairs both final characters, so both leave the prefixes. Adding one to dp[i - 1][j] may pair b[j - 1] a second time: 'aa' and 'a' would score 2."),
    "fill-partition-end": ("fill", "Greedy", "Extend to the last occurrence",
        "Split s into as many parts as possible so each letter appears in only one part. Return the part sizes. Fill the extension of the current part.",
        "def partition(s):\n    last = {ch: i for i, ch in enumerate(s)}\n    sizes, start, end = [], 0, 0\n    for i, ch in enumerate(s):\n        end = max(end, ___)\n        if i == end:\n            sizes.append(end - start + 1)\n            start = i + 1\n    return sizes",
        ["last[ch]", "i", "last[s[start]]", "end + 1"],
        "Every letter in the part must have its final occurrence inside it, so extend end to the latest last occurrence seen. Reaching end means the part can close."),
    "fill-insert-before": ("fill", "Intervals", "Copy the intervals entirely before",
        "Insert a closed interval into sorted, disjoint closed intervals, merging where they overlap or touch. Fill the condition for copying an interval unchanged before the merge.",
        "def insert(intervals, new):\n    out, i = [], 0\n    while i < len(intervals) and ___:\n        out.append(intervals[i])\n        i += 1\n    start, end = new\n    while i < len(intervals) and intervals[i][0] <= end:\n        start = min(start, intervals[i][0])\n        end = max(end, intervals[i][1])\n        i += 1\n    return out + [[start, end]] + intervals[i:]",
        ["intervals[i][1] < new[0]", "intervals[i][0] < new[0]", "intervals[i][1] <= new[0]", "intervals[i][0] < new[1]"],
        "An interval is safely before only if it ends before the new one starts. Starting earlier is not enough, since it may still overlap; an interval ending exactly at new[0] touches and must merge."),
    "fill-pascal-row": ("fill", "Math & Geometry", "Each entry sums the two above",
        "Return row n of Pascal's triangle (row 0 is [1]). Fill each interior entry of the next row.",
        "def pascal(n):\n    row = [1]\n    for _ in range(n):\n        row = [1] + [___ for i in range(len(row) - 1)] + [1]\n    return row",
        ["row[i] + row[i + 1]", "row[i] * 2", "row[i] + i", "row[i + 1]"],
        "Entry i + 1 of the next row is the sum of the two entries above it, row[i] and row[i + 1]. Doubling works only in the symmetric center."),
    "fill-reverse-bits": ("fill", "Bit Manipulation", "Move the low bit to the other end",
        "Reverse the 32-bit binary representation of 0 <= n < 2³². Fill the bit shifted into result.",
        "def reverse_bits(n):\n    result = 0\n    for _ in range(32):\n        result = (result << 1) | ___\n        n >>= 1\n    return result",
        ["n & 1", "n", "n % 10", "(n >> 1) & 1"],
        "Take n's lowest bit each step and append it to result. After 32 steps the first bit taken has moved to the top."),

    "approach-stream-k": ("approach", "Heap / Priority Queue", "A running kth-largest value",
        "Integers arrive in a stream. After at least k arrivals, report the kth-largest value after each arrival, counting duplicates. Which structure uses O(k) space and O(log k) update time for k >= 2?", "",
        ["A min-heap of the largest k values; its root is the kth largest.", "A max-heap containing every value seen so far.", "A sorted list of the largest k values, inserting by shifting entries.", "A set of the largest distinct values."],
        "The smallest of the retained k largest values is the answer. Discard the minimum on overflow. A full heap grows with the stream, a sorted list has linear shifts, and a set loses duplicate ranks."),
    "approach-median": ("approach", "Heap / Priority Queue", "Maintain the middle of a stream",
        "Report an exact median after every integer insertion, with O(log n) insertion and O(1) median lookup. Which representation meets those bounds?", "",
        ["A max-heap for the lower half and min-heap for the upper half, balanced in size and ordered across the boundary.", "One min-heap of all values; read its root.", "An unsorted list; sort a copy for each median query.", "A running sum and count; divide them for the median."],
        "The middle one or two values sit at the two heap roots. Rebalancing moves at most a constant number of elements per insertion. A mean is not a median."),
    "approach-connectivity": ("approach", "Graphs", "Connectivity as edges arrive",
        "An undirected graph receives edge additions and many queries asking whether two vertices are connected. No deletions occur. Which structure supports near-constant amortized work per operation after initialization?", "",
        ["Disjoint sets with path compression and union by size or rank.", "Run a fresh BFS across the graph for every query.", "Compare the two vertices' degrees.", "Store only each vertex's most recently added neighbor."],
        "Union the endpoint components on each addition; compare roots on each query. With compression and weighted union, operations take inverse-Ackermann amortized time. Degrees and individual neighbors do not encode connectivity."),
    "approach-topological": ("approach", "Graphs", "A dependency cycle",
        "Kahn's algorithm starts from all zero-indegree vertices and processes only 7 of a directed graph's 10 vertices before the queue empties. All edges were counted correctly. What follows?", "",
        ["The graph contains a directed cycle; the remaining vertices are on a cycle or blocked downstream of one.", "All three remaining vertices must themselves lie on a cycle.", "The graph is acyclic but disconnected.", "Every vertex must be part of a single cycle."],
        "Every nonempty finite DAG has a zero-indegree vertex, so an exhausted queue with vertices remaining implies a cycle. A remaining vertex can also simply depend on a cycle; it need not lie on one."),
    "approach-weighted": ("approach", "Advanced Graphs", "Unequal, nonnegative edge costs",
        "Find single-source shortest paths in a graph whose edge weights are nonnegative but not all equal. Which listed algorithm is correct in general?", "",
        ["Dijkstra: extract the smallest tentative distance from a min-priority queue and relax outgoing edges.", "Ordinary FIFO BFS, finalizing each vertex on first discovery.", "DFS, retaining only the first path to each vertex.", "Choose the cheapest outgoing edge at each step without considering alternatives."],
        "Nonnegative edges make the minimum tentative distance safe to finalize when extracted. First discovery can still be improved later, so marking a vertex final when it is merely enqueued is not enough."),
    "approach-dag-negative": ("approach", "Advanced Graphs", "Negative weights in a DAG",
        "A directed acyclic graph may have negative edge weights. Find single-source shortest paths in O(V + E). Which approach meets the requirement?", "",
        ["Process vertices in topological order and relax outgoing edges from reachable vertices.", "Use FIFO BFS and count edges.", "Use ordinary Dijkstra, finalizing a vertex on its first extraction.", "Run V - 1 full relaxation passes over every edge."],
        "Topological order puts every possible predecessor before its successor, so each edge needs one relaxation regardless of weight sign. Bellman-Ford's full passes are correct but do not meet the requested linear bound."),
    "approach-trie-prefix": ("approach", "Tries", "Repeated prefix existence queries",
        "After storing many lowercase words, answer whether any stored word begins with prefix p. Query time should be O(len(p)), independent of the number of words, without storing every prefix as a separate string. Which fits?", "",
        ["A trie: follow one edge per character, and succeed if the full prefix path exists.", "A hash set of whole words, testing only whether p is in the set.", "An unsorted list of words, scanning each for a matching prefix.", "A frequency map of individual letters across all words."],
        "A trie shares prefix paths. A whole-word set misses prefixes that are not complete words, while a scan depends on the number of words and letter frequencies lose order."),
    "approach-bst-global": ("approach", "Trees", "A descendant crosses an ancestor",
        "A root has value 10. Its left child is 5, and that child's right child is 12. All other children are empty. What correctly assesses the strict BST property?", "",
        ["Invalid: 12 is in 10's left subtree, so checking ancestor bounds exposes the violation.", "Valid: each immediate left child is smaller and each immediate right child is larger.", "Valid: all three values are distinct.", "Invalid solely because the tree is not height-balanced."],
        "BST constraints apply to entire subtrees, not only parent-child comparisons. A descendant of the root's left child must remain below 10. Balance is a separate property."),
    "approach-list-cycle": ("approach", "Linked List", "Detect a cycle without extra storage",
        "Detect whether a singly linked list has a cycle in O(n) time and O(1) extra space, without modifying nodes. Which approach meets all constraints?", "",
        ["A slow pointer moving one link and a fast pointer moving two; compare node identities after advancing.", "Store every visited node in a hash set.", "Compare the values of adjacent nodes and stop on equal values.", "Mark visited nodes by replacing their next pointers."],
        "Within a cycle the faster pointer eventually catches the slower one. Repeated values do not imply repeated nodes. A visited set uses extra space; rewiring violates the no-modification constraint."),
    "approach-interval-greedy": ("approach", "Greedy", "Fit the most appointments",
        "Choose the maximum number of unweighted intervals without overlap. Each has start < end; an interval may start when another ends. Which greedy rule is correct?", "",
        ["Sort by increasing finish time and take each interval whose start is at least the last selected end.", "Always choose the shortest remaining duration first.", "Sort by increasing start time and take the first compatible interval.", "Always choose the interval overlapping the fewest other intervals, without an exchange argument."],
        "The earliest finish leaves at least as much room for every later appointment. Replacing the first interval of an optimum with an earliest-finishing one cannot reduce the achievable count."),
    "approach-range-updates": ("approach", "Arrays & Hashing", "Range sums after point updates",
        "An array needs frequent point-value changes and inclusive range-sum queries. Which listed structure provides O(log n) for both operations with O(n) storage?", "",
        ["A Fenwick tree: update by the value delta and subtract two prefix-sum queries.", "A static prefix-sum array rebuilt after every change.", "The original array with a loop over the queried range.", "A single total sum for the whole array."],
        "A Fenwick tree stores overlapping partial sums, touching logarithmically many entries per update or prefix query. Static prefix sums give fast queries but need linear work to repair after a point change."),
    "approach-reusable-item": ("approach", "2-D DP", "When one item becomes reusable",
        "A 1-D knapsack DP maximizes value with capacity at most C. Item weights are positive and values nonnegative. If each item changes from single-use to unlimited-use, which loop change allows reuse?", "",
        ["For each item, scan capacities upward from its weight to C, so a state may include that same item already.", "For each item, keep scanning capacities downward from C to its weight.", "Keep downward scanning but initialize every dp entry to 1.", "Discard the capacity dimension and keep only the largest item value."],
        "An upward scan can read a smaller-capacity state updated earlier for the same item. A downward scan preserves the single-use restriction by reading states that predate the item."),
    "approach-multi-source": ("approach", "Graphs", "Distance to the nearest source",
        "In an unweighted grid with blocked cells, find each reachable cell's shortest distance to any of several sources in O(rows × columns). Which approach fits?", "",
        ["Put all sources into one BFS queue at distance zero, mark them, and expand layers together.", "Run a separate full BFS from every source and take minima.", "Use DFS and finalize a cell on first discovery.", "Use Manhattan distance to the nearest source, ignoring walls."],
        "One multi-source BFS expands all distance-zero fronts together and visits each cell once. Separate BFS runs multiply the work by the number of sources; walls can invalidate Manhattan distance."),
    "approach-monotone-answer": ("approach", "Binary Search", "Search over a feasible capacity",
        "For integer capacities 1..M, feasible(c) is false below a threshold and true from that threshold onward. feasible(M) is true. How can you find the smallest feasible capacity with O(log M) predicate calls?", "",
        ["Binary-search the boundary: a feasible midpoint keeps the left half including mid; an infeasible midpoint discards mid and everything below it.", "Scan capacities from 1 until feasible becomes true.", "Binary-search while moving right whenever the midpoint is feasible.", "Evaluate feasible only at 1 and M, then average the endpoints."],
        "Monotonicity justifies discarding half the candidate capacities on each check. Keep a feasible midpoint because it might be the first feasible capacity."),
    "approach-subsequence": ("approach", "2-D DP", "Subsequence or substring?",
        "Find the length of the longest common subsequence of two strings. Characters may be skipped. For prefix DP, what should happen when the final characters differ?", "",
        ["Take max(dp[i - 1][j], dp[i][j - 1]): skip one of the two final characters.", "Set dp[i][j] to zero, restarting a contiguous match.", "Always take dp[i - 1][j - 1] + 1.", "Add dp[i - 1][j] and dp[i][j - 1]."],
        "A mismatch can be resolved by skipping either final character, so choose the better prefix result. Resetting to zero is the mismatch rule for a common-substring suffix DP, which requires contiguity."),

    "approach-three-sum": ("approach", "Two Pointers", "From pairs to triples",
        "Find all unique triples summing to zero in O(n²) time and O(1) extra space besides the output and sorting. Which approach fits?", "",
        ["Sort, then for each anchor run two pointers inward over the rest, skipping repeated values.", "Check every triple of positions, deduplicating with a set.", "Put every pairwise sum in a hash map, then look up each value's negation.", "Sort, then binary-search the third value for every pair."],
        "Sorting lets each anchor's inner search be a linear two-pointer scan, giving O(n²) total. A pair-sum map uses O(n²) space; binary search per pair costs O(n² log n)."),
    "approach-trapped-water": ("approach", "Two Pointers", "Water bounded by the lower side",
        "Compute trapped rainwater over an elevation map in O(n) time and O(1) extra space. Which approach fits?", "",
        ["Two pointers with running left and right maxima; advance the side whose maximum is lower, since that maximum bounds its water.", "For each bar, scan left and right for the tallest walls.", "Precompute prefix and suffix maximum arrays.", "Use a max-heap of bar heights."],
        "Water above a bar is min(tallest left, tallest right) minus its height. On the side with the lower running maximum, that maximum is the binding bound. Prefix and suffix arrays are also O(n) but use O(n) space."),
    "approach-min-window": ("approach", "Sliding Window", "Cover every required letter",
        "Find the shortest substring of s containing every character of t, with multiplicity, in O(len(s) + len(t)) time. Which approach fits?", "",
        ["A variable window: expand right until counts cover t, then shrink left while they still do, tracking how many requirements are met.", "A fixed window of length len(t) slid across s.", "Check every substring of s against t's counts.", "Sort s and t and compare them."],
        "The shortest window can be longer than t, so it cannot be fixed-size. Each pointer only moves forward, and a satisfied-requirements counter avoids rescanning the count map."),
    "approach-anagram-window": ("approach", "Sliding Window", "Find every anagram",
        "Return every start index in s where a substring is an anagram of p (lowercase letters) in O(len(s)) time. Which approach fits?", "",
        ["A fixed window of length len(p) with letter counts, adding the entering letter and removing the leaving one.", "Sort every substring of length len(p) and compare it with sorted p.", "A variable window that grows until it contains every letter of p.", "A hash set of p's letters."],
        "An anagram has exactly p's length and letter counts, so slide a fixed window and update counts in O(1). Sorting each window adds a log factor; a letter set ignores multiplicity."),
    "approach-window-max": ("approach", "Sliding Window", "Maximum of every window",
        "Report the maximum of every contiguous window of size k in O(n) total time. Which approach fits?", "",
        ["A deque of indices with decreasing values: drop the front when it leaves the window and pop smaller values from the back.", "A max-heap of the window's values, removing the outgoing value each step.", "Recompute max over each window.", "Keep one running maximum, replacing it when a larger value arrives."],
        "A smaller value behind a larger, newer one can never be a window maximum again. Each index enters and leaves the deque once. A running maximum fails when the maximum slides out."),
    "approach-next-greater": ("approach", "Stack", "Each index waits for a larger value",
        "For each position, find the next strictly greater value to its right in O(n) time. Which approach fits?", "",
        ["A monotonic stack of waiting indices: each new value pops and answers every smaller waiting value.", "For each position, scan right until a larger value.", "Sort values and read the following value in sorted order.", "Use a queue, answering the oldest waiting index first."],
        "Waiting values on the stack are nonincreasing, so a new value resolves a contiguous run from the top. Each index is pushed and popped once. Sorted order ignores position."),
    "approach-histogram": ("approach", "Stack", "Largest rectangle in a histogram",
        "Find the largest rectangle area in a histogram in O(n). Which approach fits?", "",
        ["A stack of increasing heights: popping a bar reveals the nearest shorter bars on both sides, which bound its widest rectangle.", "Two pointers moving the shorter bar inward.", "For each pair of bars, use the minimum between them.", "Sort bars by height and use the tallest."],
        "When a shorter bar arrives, each popped bar's rectangle ends here and begins after the new stack top. The container two-pointer rule applies to two walls, not to a minimum over a range."),
    "approach-rotated": ("approach", "Binary Search", "Search a rotated array",
        "A rotated ascending array of distinct values must be searched in O(log n). What does each step rely on?", "",
        ["At least one half around mid is sorted; test whether the target lies in that half's range to discard the other half.", "The whole array is sorted, so ordinary binary search works unchanged.", "First sort a copy, then binary-search it.", "Scan until the value drops, then search the remainder linearly."],
        "Rotation creates only one break, so a half that contains no break is sorted and its endpoints give a reliable range test. Sorting a copy or finding the break by scanning is linear or worse."),
    "approach-nth-from-end": ("approach", "Linked List", "Remove the nth node from the end",
        "Remove the nth node from the end of a singly linked list in one pass with O(1) extra space, including when it is the head. Which approach fits?", "",
        ["Start two pointers at a dummy node, advance the leader n + 1 steps, then move both until the leader is None.", "Store every node in an array and index from its end.", "Reverse the list, remove the nth node, reverse back.", "Advance one pointer n steps from the head, then delete it."],
        "The fixed gap leaves the trailing pointer just before the target. A dummy node handles removing the head. An array uses O(n) space; reversing twice uses extra passes."),
    "approach-lru": ("approach", "Linked List", "O(1) least-recently-used cache",
        "Implement an LRU cache where get and put run in O(1). Which structure fits?", "",
        ["A hash map from key to node in a doubly linked list ordered by recency; move a node to the front on use and evict the tail.", "A hash map alone, scanning for the oldest timestamp on eviction.", "A min-heap of timestamps.", "A singly linked list scanned on every access."],
        "The map finds a node in O(1), and a doubly linked node can be unlinked and moved in O(1). Scanning timestamps or a heap costs O(n) or O(log n)."),
    "approach-kth-bst": ("approach", "Trees", "The kth smallest in a BST",
        "Find the kth smallest value in a binary search tree of height h in O(h + k) time. Which approach fits?", "",
        ["In-order traversal, iteratively with a stack, stopping at the kth visited node.", "Pre-order traversal, stopping at the kth node.", "Collect every value, then sort them.", "Walk left k times from the root."],
        "In-order traversal visits BST values in ascending order. Collecting everything costs O(n log n). Walking left only follows the smallest values on one path."),
    "approach-lca-bst": ("approach", "Trees", "Lowest common ancestor in a BST",
        "Find the lowest common ancestor of two values present in a binary search tree in O(h). Which approach fits?", "",
        ["Walk from the root: go left if both are smaller, right if both are larger, otherwise stop at this split point.", "Record both root-to-node paths in a general tree, then compare them, ignoring BST order.", "Return the parent of the smaller value.", "Return the root, which is an ancestor of every node."],
        "The ordering tells you where both values lie. The first node separating them, or equal to one of them, is their lowest common ancestor. The root is common but not lowest."),
    "approach-word-search-trie": ("approach", "Tries", "Many words in one grid",
        "Find which of many words can be traced through adjacent letter cells in a grid. Which approach avoids a separate grid search for each word?", "",
        ["Build a trie of the words and run one DFS from each cell, following trie edges and pruning when no word has the current prefix.", "Run a separate DFS for each word.", "Put the words in a hash set and generate every grid path.", "Count the grid's letters and compare them with each word's counts."],
        "Shared prefixes are explored once, and a missing trie edge stops a path immediately. A set lookup cannot tell whether a path can still become a word; letter counts ignore adjacency."),
    "approach-k-closest": ("approach", "Heap / Priority Queue", "k closest points",
        "Return the k points nearest the origin in O(n log k) time and O(k) extra space. Which approach fits?", "",
        ["A max-heap of size k by squared distance; replace the farthest retained point when a closer one arrives.", "A min-heap of all n points, popping k times.", "Sort all points by distance.", "A min-heap of size k by distance."],
        "The heap root must be the retained point most eligible for eviction: the farthest. A full heap or sort uses more time or space; a size-k min-heap would evict the closest points."),
    "approach-perms-dupes": ("approach", "Backtracking", "Permutations with repeated values",
        "Return each distinct permutation of a list that may contain duplicates, without generating duplicates first. Which rule fits?", "",
        ["Sort, then at each depth skip a value equal to its predecessor when that predecessor is not in use.", "Generate every permutation, then deduplicate with a set.", "Skip any value already present anywhere in the path.", "Swap only adjacent elements."],
        "Among equal values, allow them to be used only in left-to-right order. Then each distinct arrangement is built once. Skipping values already on the path would forbid legitimately repeated values."),
    "approach-n-queens": ("approach", "Backtracking", "Constant-time queen checks",
        "Place one queen per row with backtracking and test each column in O(1). Which state fits?", "",
        ["Sets of used columns, r - c diagonals and r + c anti-diagonals.", "Scan every earlier row for attacks.", "Only a set of used columns.", "Only a set of used rows."],
        "Cells on the same diagonal share r - c and cells on the same anti-diagonal share r + c. Columns alone miss diagonal attacks; placing one queen per row already separates rows."),
    "approach-bipartite": ("approach", "Graphs", "Split into two sides",
        "Decide whether an undirected graph's vertices can be split into two groups with every edge crossing between them. Which approach fits?", "",
        ["BFS or DFS 2-coloring of every component; an edge between same-colored vertices proves an odd cycle.", "Check that every vertex has even degree.", "Check that the graph has no cycles.", "Topologically sort it."],
        "A graph is bipartite exactly when it has no odd cycle, and forced alternating colors detect one. Even cycles are fine, so requiring acyclicity is too strict. Topological sorting applies to directed graphs."),
    "approach-clone-graph": ("approach", "Graphs", "Copy a graph with cycles",
        "Deep-copy a connected undirected graph from one node, preserving its cycles. Which approach fits?", "",
        ["DFS or BFS with a map from original to copy, recording each copy before visiting its neighbors.", "Recursively copy neighbors without a visited map.", "Copy node values into a list and rebuild a path.", "Reuse the original neighbor lists in each copy."],
        "The map ends recursion around cycles and makes each original correspond to exactly one copy. Sharing neighbor lists would connect the copy back to the original graph."),
    "approach-mst": ("approach", "Advanced Graphs", "Connect every point cheaply",
        "Connect all vertices of a weighted, undirected, connected graph with minimum total edge weight. Which approach fits?", "",
        ["Kruskal: sort edges and add each one joining two different disjoint-set components.", "Dijkstra's shortest-path tree from one vertex.", "Always add each vertex's cheapest incident edge, then stop.", "BFS tree from one vertex."],
        "The lightest edge crossing any cut is safe for a minimum spanning tree. A shortest-path tree minimizes each vertex's distance, not the total. Cheapest incident edges alone can leave components disconnected."),
    "approach-k-stops": ("approach", "Advanced Graphs", "Cheapest price with at most k stops",
        "Find the cheapest route using at most k intermediate stops. Prices are positive. Which approach respects the limit directly?", "",
        ["k + 1 rounds of Bellman-Ford relaxation, reading only the previous round's distances in each round.", "Ordinary Dijkstra by price, ignoring stop count.", "BFS by edge count, keeping only the first price found.", "DFS over every route."],
        "Round i finds cheapest routes of at most i edges. Reading the previous round prevents one round chaining several edges. Dijkstra can discard a pricier route that has fewer stops."),
    "approach-word-break": ("approach", "1-D DP", "Split into dictionary words",
        "Decide whether s can be split into a sequence of dictionary words, with reuse allowed. Which approach fits?", "",
        ["DP over prefixes: ok[i] is true if some j has ok[j] and s[j:i] in the dictionary set.", "Greedily take the longest dictionary prefix each time.", "Check whether each letter appears in some word.", "Greedily take the shortest dictionary prefix each time."],
        "A choice at one split affects which later splits are possible, so greedy prefixes fail (for example words ['a', 'ab', 'bc'] and s = 'abc'). DP remembers every reachable split point."),
    "approach-coin-change": ("approach", "1-D DP", "Fewest coins for any coin system",
        "Find the fewest coins totaling an amount with arbitrary positive, reusable denominations. Which approach is always correct?", "",
        ["DP over amounts: best[a] = 1 + min(best[a - coin]) over coins not exceeding a.", "Take the largest coin that fits until done.", "Take the smallest coin repeatedly.", "Count unordered combinations and return that count."],
        "Largest-first works only for special coin systems; with [1, 3, 4] and 6 it uses three coins instead of two. DP considers every final coin choice."),
    "approach-lis-fast": ("approach", "1-D DP", "Longest increasing subsequence in O(n log n)",
        "Find the length of the longest strictly increasing subsequence in O(n log n). Which approach fits?", "",
        ["Keep tails[k], the smallest possible tail of an increasing subsequence of length k + 1; binary-search where each value goes.", "Sort the values and count distinct values.", "Track the longest run of adjacent increases.", "A monotonic stack that pops larger values."],
        "Smaller tails leave more room to extend, and tails stays sorted, so each value is placed by binary search. tails need not be an actual subsequence; only its length is the answer."),
    "approach-edit-distance": ("approach", "2-D DP", "Turn one word into another",
        "Find the fewest single-character insertions, deletions and replacements turning one string into another. Which approach fits?", "",
        ["Prefix DP: matching last characters reuse the diagonal; otherwise add one to the best of insert, delete and replace.", "Count characters that differ at the same positions.", "Compute the longest common substring.", "Take the difference in lengths."],
        "Positional differences ignore insertions that shift later characters. The DP considers the final operation in every possible way and solves each pair of prefixes once."),
    "approach-jump-game": ("approach", "Greedy", "Can you reach the end?",
        "nums[i] is the maximum jump from i. Decide in O(n) time and O(1) space whether the last index is reachable. Which approach fits?", "",
        ["Scan left to right keeping the farthest reachable index; fail when an index is beyond it.", "Always take the longest jump from the current index.", "BFS over every jump.", "Fail whenever a zero appears."],
        "Every index up to the farthest reachable point can be reached. Always jumping farthest can land on a dead end. A zero matters only if nothing jumps past it."),
    "approach-meeting-rooms": ("approach", "Intervals", "Minimum meeting rooms",
        "Find the fewest rooms needed for a set of meetings in O(n log n). A meeting may start when another ends. Which approach fits?", "",
        ["Sort by start and keep a min-heap of end times; reuse the earliest-ending room if it is free.", "Sort by start and count overlaps with only the previous meeting.", "Return the largest meeting duration.", "Merge overlapping intervals and count the merged groups."],
        "The heap size is the number of simultaneously occupied rooms. Merging produces busy periods, which is not the same as the number of concurrent meetings within them."),
    "approach-insert-interval": ("approach", "Intervals", "Insert into sorted intervals",
        "Insert a new interval into sorted, non-overlapping intervals, merging as needed, in O(n). Which approach fits?", "",
        ["One pass: copy intervals ending before it, merge every overlapping one into it, then copy the rest.", "Append it, sort everything, then merge.", "Binary-search its start and insert it without merging.", "Merge it with only the next interval."],
        "The input is already sorted, so the three phases give O(n). Re-sorting costs O(n log n); one insertion can overlap many existing intervals."),
    "approach-matrix-spiral": ("approach", "Math & Geometry", "Spiral traversal",
        "Return a matrix's values in clockwise spiral order in O(rows × columns) time. Which approach fits?", "",
        ["Shrink top, bottom, left and right boundaries after each side, checking that bounds have not crossed before the last two sides.", "Sort the values.", "Read rows alternately left-to-right and right-to-left.", "Transpose the matrix, then read it by rows."],
        "Boundaries mark the unvisited rectangle. Checking them before the bottom row and left column avoids repeating values in a single remaining row or column. Zigzag rows are not a spiral."),
    "approach-sum-no-plus": ("approach", "Bit Manipulation", "Addition without +",
        "Add two integers using bitwise operations only. Which idea is correct?", "",
        ["XOR gives the sum without carries and AND shifted left gives the carries; repeat until no carry remains (masking in Python for negatives).", "OR the numbers together.", "XOR once.", "AND the numbers, then shift right."],
        "Bitwise addition is carry propagation. XOR alone drops carries; OR merges bits incorrectly when both are set. Python integers are unbounded, so negative values need a fixed-width mask."),
    "approach-counting-bits": ("approach", "Bit Manipulation", "Bit counts for 0..n",
        "Return the number of 1 bits for every integer from 0 through n in O(n) total time. Which recurrence fits?", "",
        ["bits[i] = bits[i >> 1] + (i & 1): i shares all bits with i // 2 except its last.", "bits[i] = bits[i - 1] + 1.", "bits[i] = i % 2.", "bits[i] = bits[i // 2] * 2."],
        "Shifting right removes only the lowest bit, which was already computed. Adding one to the previous count fails at every carry, such as from 3 to 4."),
    "approach-encode-strings": ("approach", "Arrays & Hashing", "Encode arbitrary strings",
        "Encode a list of strings into one string and decode it exactly. Strings may contain any character, including separators. Which scheme is always reversible?", "",
        ["Prefix each string with its length and a delimiter, then read that many characters when decoding.", "Join with a comma and split on commas.", "Join with a rare character sequence.", "Escape nothing and store the count of strings first."],
        "A length prefix tells the decoder exactly where each string ends, whatever it contains. Any plain delimiter can appear inside a string."),
    "approach-longest-consecutive": ("approach", "Arrays & Hashing", "Longest consecutive run in O(n)",
        "Find the length of the longest run of consecutive integers in an unsorted list in O(n) expected time. Which approach fits?", "",
        ["Put values in a set and count upward only from values x where x - 1 is absent.", "Sort, then scan.", "Count upward from every value in the set.", "Use a sliding window over the original order."],
        "Starting only at run beginnings means each value is visited a constant number of times. Sorting costs O(n log n); counting from every value can be quadratic."),
    "approach-sudoku-boxes": ("approach", "Arrays & Hashing", "Validate a Sudoku in one pass",
        "Check a partially filled 9×9 board for repeated digits in any row, column or 3×3 box, in one pass. Which bookkeeping fits?", "",
        ["Sets per row, per column and per box, with box index (r // 3, c // 3).", "One set per row only.", "Sort each row and column.", "Check that every row sums to 45."],
        "Integer division maps each cell to its box. Sums cannot detect duplicates in a partial board; row checks alone miss column and box conflicts."),
    "approach-car-fleet": ("approach", "Stack", "Cars that catch up",
        "Cars on a one-lane road drive toward a target; a faster car that catches a slower one joins its fleet. Count fleets arriving. Which approach fits?", "",
        ["Sort by position from closest to the target, compute each arrival time, and start a new fleet when a time exceeds the current fleet's time.", "Sort by speed and count distinct speeds.", "Simulate every time unit.", "Count cars that are faster than the next car."],
        "A car can only be blocked by the fleet ahead. If it would arrive no sooner than that fleet, it joins it; a later arrival time starts a new fleet."),
    "approach-banana-speed": ("approach", "Binary Search", "Smallest workable speed",
        "Find the smallest eating speed that finishes all piles within h hours. Which approach fits?", "",
        ["Binary-search speeds 1..max(piles), since finishing is monotonic in speed; each check sums ceil(pile / speed).", "Use total bananas divided by h.", "Try every speed from max(piles) downward.", "Sort piles and use the median."],
        "Faster speeds never take longer, so feasibility is monotonic. Average rate ignores that each pile costs whole hours."),
    "approach-duplicate-cycle": ("approach", "Linked List", "Find a duplicate without extra space",
        "An array of n + 1 values in 1..n has one repeated value. Find it in O(n) time and O(1) space without modifying the array. Which approach fits?", "",
        ["Treat i → nums[i] as links and use Floyd's cycle detection; the cycle entrance is the duplicate.", "Sort the array and compare neighbors.", "Use a set of seen values.", "Sum the values and subtract 1 + … + n."],
        "Two indices point to the duplicate value, creating a cycle entrance. The sum trick fails when the value repeats more than twice; sorting modifies and a set uses space."),
    "approach-copy-random": ("approach", "Linked List", "Copy a list with random pointers",
        "Deep-copy a linked list whose nodes have next and random pointers. Which approach correctly copies both?", "",
        ["Map each original node to its copy in one pass, then set each copy's next and random through the map.", "Copy next pointers only, reusing original random targets.", "Copy values into an array and rebuild.", "Recursively copy random pointers without memoization."],
        "Random pointers can point anywhere, including forward or back to a node already copied. The map gives exactly one copy per original."),
    "approach-max-path-sum": ("approach", "Trees", "Best path anywhere in the tree",
        "Find the maximum sum of any path between two nodes in a binary tree with negative values. Which recursion fits?", "",
        ["Return the best downward branch (clamping negative children to 0); update the answer with node + both clamped branches.", "Return the best root-to-leaf path sum.", "Sum all positive values.", "Return node + both branches to the parent."],
        "A path can bend at only one node, so the parent can extend just one branch. Negative branches are better omitted."),
    "approach-serialize-tree": ("approach", "Trees", "Serialize a tree exactly",
        "Serialize a binary tree with possibly repeated values so it can be rebuilt exactly. Which encoding fits?", "",
        ["Preorder with explicit null markers.", "Inorder values only.", "Preorder values only.", "Level-order values, skipping nulls."],
        "Without null markers, different shapes produce the same sequence. With them, preorder determines each subtree's boundaries."),
    "approach-word-ladder": ("approach", "Graphs", "Fewest one-letter changes",
        "Find the fewest one-letter transformations from begin to end, each word in a dictionary. Which approach fits?", "",
        ["BFS over words, finding neighbors through wildcard patterns such as h*t.", "DFS, returning the first path found.", "Greedy: change the letter that matches end.", "Sort the dictionary and binary-search."],
        "Every transformation costs one step, so BFS finds the fewest. Wildcard buckets list neighbors without comparing every pair of words."),
    "approach-alien-order": ("approach", "Advanced Graphs", "An unknown alphabet",
        "Given words sorted in an unknown alphabet, derive a valid letter order or report it impossible. Which approach fits?", "",
        ["For each adjacent pair, add an edge from the first differing letters, reject a word followed by its own proper prefix, then topologically sort.", "Sort the letters by first appearance.", "Compare every letter of each adjacent pair position by position.", "Count letter frequencies."],
        "Only the first difference between adjacent words gives information. Later positions are unconstrained, and a cycle or a prefix placed after its extension makes the order invalid."),
    "approach-rising-water": ("approach", "Advanced Graphs", "Minimize the highest cell",
        "Find the smallest time t at which you can walk from the top-left to the bottom-right of a grid through cells with elevation <= t. Which approach fits?", "",
        ["Dijkstra-like search keyed by the maximum elevation so far, always expanding the smallest.", "BFS minimizing the number of steps.", "DP moving only right and down.", "Sum elevations along the path."],
        "The cost of a path is its maximum elevation, which a min-heap on that maximum handles correctly. Paths may need to move up or left."),
    "approach-palindromic-substrings": ("approach", "1-D DP", "Count palindromic substrings",
        "Count palindromic substrings in O(n²) time and O(1) space. Which approach fits?", "",
        ["Expand around each of the 2n - 1 centers, counting while the ends match.", "Check every substring by reversing it.", "Reverse the string and compute its LCS with itself.", "Count repeated characters."],
        "Every palindrome has a center, one character or a gap. Expanding stops at the first mismatch; brute force takes O(n³)."),
    "approach-target-sum": ("approach", "2-D DP", "Signs that reach a target",
        "Assign + or - to each nonnegative value to reach target. Which reformulation leads to a subset-count DP?", "",
        ["The + set must sum to (total + target) / 2, so count subsets with that sum (zero if odd or negative).", "Greedily add the largest remaining value.", "Count subsets summing to target.", "Sort and use two pointers."],
        "P - N = target and P + N = total give P = (total + target) / 2. The problem becomes a 0/1 subset-count knapsack."),
    "approach-burst-balloons": ("approach", "2-D DP", "Choose the last balloon",
        "Maximize coins from bursting balloons, where each burst scores its value times its current neighbors. Which DP split fits?", "",
        ["Interval DP choosing the last balloon burst in (left, right); its neighbors are then the fixed boundaries.", "Choose the first balloon burst in each interval.", "Greedily burst the smallest value first.", "1-D DP over prefixes."],
        "Choosing the last balloon makes its neighbors known and the two sides independent. Choosing the first leaves neighbors changing."),
    "approach-hand-straights": ("approach", "Greedy", "Groups of consecutive cards",
        "Decide whether cards can be split into groups of k consecutive values. Which approach fits?", "",
        ["Count values; repeatedly start a group at the smallest remaining value and consume k consecutive values.", "Sort and check adjacent differences are 1.", "Check the count is divisible by k.", "Start groups at the largest value, allowing gaps."],
        "The smallest remaining card can only start a group, so starting there is forced. Divisibility is necessary but not sufficient."),
    "approach-min-interval-query": ("approach", "Intervals", "Smallest interval containing each query",
        "For each query point, find the size of the smallest interval containing it, in O((n + q) log(n + q)). Which approach fits?", "",
        ["Sort intervals and queries; for each query, push intervals starting by it into a min-heap by size and pop those ending before it.", "Scan all intervals for each query.", "Merge intervals first.", "Binary-search the interval with the nearest start."],
        "Queries in increasing order let intervals enter once and leave once. Merging loses sizes; the nearest start may not contain the point."),
    "approach-multiply-strings": ("approach", "Math & Geometry", "Multiply numbers stored as strings",
        "Multiply two nonnegative integers given as digit strings without converting them to ints. Which approach fits?", "",
        ["Schoolbook multiplication into an array of length m + n, adding each digit product at position i + j + 1 and carrying.", "Add one number to itself repeatedly.", "Multiply digit by digit without carries.", "Concatenate the digits."],
        "Digits i and j contribute to position i + j + 1 of the product. Repeated addition takes time proportional to the value, not its digits."),
    "approach-reverse-overflow": ("approach", "Math & Geometry", "Reverse within 32 bits",
        "Reverse a signed 32-bit integer's digits, returning 0 if the result overflows, using only 32-bit arithmetic. Which check fits?", "",
        ["Before appending a digit, check that rev is within INT_MAX // 10 (and the last digit bound).", "Reverse first, then check the result.", "Use a string and compare lengths.", "Check whether the input is larger than INT_MAX."],
        "With only 32-bit arithmetic, the overflow happens during the multiplication, so check before it. A valid input can still reverse out of range."),
    "approach-missing-xor": ("approach", "Bit Manipulation", "Missing number via XOR",
        "nums contains distinct values from 0..n with one missing. Find it in O(n) time and O(1) space without overflow concerns. Which idea fits?", "",
        ["XOR all indices 0..n with all values; pairs cancel and the missing value remains.", "Sort and scan.", "Use a set of values.", "Take the maximum plus one."],
        "x ^ x = 0, so every present value cancels with its index. The maximum plus one fails when the missing value is inside the range."),
}
